<?php

/**
 * @file
 * Helper module for MailChimp Helper tests.
 */

use Drupal\mailchimphelper\Tests\MailChimp\MailchimpLists;

/**
 * Implements hook_init().
 *
 * Replaces MailChimpLists class to use.
 */
function mailchimphelpertest_init() {
  // Override the MailChimp list class to use.
  mailchimp_get_api_object('MailchimpLists');
  $list = &drupal_static('mailchimp_get_api_object');
  if (!($list instanceof MailchimpLists)) {
    $list = new MailchimpLists('MAILCHIMP_TEST_API_KEY', 'apikey', 60);
  }
}

/**
 * Implements hook_rules_action_info().
 *
 * Force Rules to discover class based plugins.
 *
 * Because RulesAbstractPlugin::includeFiles() statically caches if files already
 * have been included without a way to reset that cache during tests.
 *
 * @see RulesAbstractPlugin::includeFiles()
 */
function mailchimphelpertest_rules_action_info() {
  $dirs = array();
  foreach (module_implements('rules_directory') as $module) {
    // Include all files once, so the discovery can find them.
    $result = module_invoke($module, 'rules_directory');
    if (!is_array($result)) {
      $result = array($module => $result);
    }
    $dirs += $result;
  }
  foreach ($dirs as $module => $directory) {
    foreach (glob(drupal_get_path('module', $module) . "/$directory/*.{inc,php}", GLOB_BRACE) as $filename) {
      include_once $filename;
    }
  }

  return array();
}
